### PR TITLE
Fix error where to_currency_code/1 would break for countries with no …

### PR DESCRIPTION
**Pull request by Stroemgren**
…currencies

### CODE REVIEW

**Comment by Stroemgren** [comment]
https://github.com/elixir-cldr/cldr_territories/issues/47

**Comment by Schultzer** [comment]
I think we should use @kipcole9 solution, that would align it with the rest of the codebase 

https://github.com/elixir-cldr/cldr_territories/issues/47#issuecomment-2495664238

You would need to write tests for this, but there should be plenty of similar functions, dealing with missing data that you can draw inspiration from!

**Comment by Stroemgren** [comment]
Now returning Cldr.UnknownCurrencyError.

I added a test block to the test file and a single test entry to the doctest to serve as documentation as well.

**Review by Schultzer — APPROVED** [review]
Awesome 👏 ❤️🚀🎉

**Pull request merged**
